---
# Source: voting-app/templates/postgresql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-voting-app-db-pvc
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - 
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
# Source: voting-app/templates/redis-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-voting-app-redis-pvc
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - 
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
# Source: voting-app/templates/postgresql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-voting-app-db
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: postgresql
---
# Source: voting-app/templates/redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-voting-app-redis
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: redis
---
# Source: voting-app/templates/result-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-voting-app-result
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: result
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: result
---
# Source: voting-app/templates/vote-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-voting-app-vote
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: vote
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: vote
---
# Source: voting-app/templates/postgresql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-voting-app-db
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-app
      app.kubernetes.io/instance: test
      app.kubernetes.io/component: postgresql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: voting-app
        app.kubernetes.io/instance: test
        app.kubernetes.io/component: postgresql
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: postgresql
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          image: "postgres:15-alpine"
          imagePullPolicy: Always
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: DB_AUTH
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: DB_AUTH
                  key: 
            - name: POSTGRES_DB
              value: postgres
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: test-voting-app-db-pvc
---
# Source: voting-app/templates/redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-voting-app-redis
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-app
      app.kubernetes.io/instance: test
      app.kubernetes.io/component: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: voting-app
        app.kubernetes.io/instance: test
        app.kubernetes.io/component: redis
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: redis
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          image: "redis:alpine"
          imagePullPolicy: Always
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: REDIS_AUTH
                  key: REDIS_PASSWORD
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: test-voting-app-redis-pvc
---
# Source: voting-app/templates/result-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-voting-app-result
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: result
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-app
      app.kubernetes.io/instance: test
      app.kubernetes.io/component: result
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: voting-app
        app.kubernetes.io/instance: test
        app.kubernetes.io/component: result
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: result
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          image: "dockersamples/examplevotingapp_result:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - result
              topologyKey: kubernetes.io/hostname
            weight: 100
---
# Source: voting-app/templates/vote-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-voting-app-vote
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: vote
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-app
      app.kubernetes.io/instance: test
      app.kubernetes.io/component: vote
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: voting-app
        app.kubernetes.io/instance: test
        app.kubernetes.io/component: vote
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: vote
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          image: "dockersamples/examplevotingapp_vote:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - vote
              topologyKey: kubernetes.io/hostname
            weight: 100
---
# Source: voting-app/templates/worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-voting-app-worker
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-app
      app.kubernetes.io/instance: test
      app.kubernetes.io/component: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: voting-app
        app.kubernetes.io/instance: test
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: worker
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          image: "dockersamples/examplevotingapp_worker:0.0.1"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
---
# Source: voting-app/templates/result-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-voting-app-result
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: result
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-voting-app-result
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: voting-app/templates/vote-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-voting-app-vote
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-voting-app-vote
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: voting-app/templates/worker-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-voting-app-worker
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-voting-app-worker
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: voting-app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "test-voting-app-test-connection"
  labels:
    helm.sh/chart: voting-app-0.1.0
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['test-voting-app-vote:8080']
  restartPolicy: Never
