apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.vote.fullname" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vote
  {{- with .Values.vote.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.vote.service.type "NodePort") .Values.vote.service.nodePort }}
      nodePort: {{ .Values.vote.service.nodePort }}
      {{- end }}
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vote
