{{- if .Values.vote.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "voting-app.vote.fullname" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "voting-app.vote.fullname" . }}
  minReplicas: {{ .Values.vote.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vote.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.vote.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.vote.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.vote.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.vote.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
